// Auto-generated by scripts/sync-resume.ts — do not edit manually.
// Update public/resume.pdf then run `npm run sync-resume` to regenerate.

export type Experience = {
  company: string
  role: string
  period: string
  bullets: string[]
}

export type Education = {
  school: string
  degree: string
  year: string
}

export type ResumeData = {
  hasDocx: boolean
  experience: Experience[]
  education: Education[]
}

export const resume: ResumeData = {
  "hasDocx": false,
  "experience": [
    {
      "company": "Deloitte, Atlanta, GA",
      "role": "Full Stack Web Developer",
      "period": "May 2023 – Jan 2026",
      "bullets": [
        "Client: The Home Depot — Ecommerce Platform: Developed and optimized React/Next.js components for a high-traffic ecommerce platform serving millions of monthly users across product discovery and purchase journeys.",
        "Built reusable product and content modules used across product listing, search, and checkout flows, reducing UI development time by 30%.",
        "Improved Core Web Vitals and page load performance by implementing SSR, caching, and code-splitting, reducing load times by 25–30%.",
        "Partnered with product, UX, and analytics teams to deliver customer-facing features that improved engagement and supported A/B testing and data-driven decisions.",
        "Contributed to a scalable design system and helped modernize legacy frontend architecture into modular React/Next.js applications.",
        "Delivered customer-facing modules for a government platform used by 10K+ users, collaborating with backend teams to define API contracts and optimize Next.js + Spring Boot integrations.",
        "Developed and maintained large-scale React/Next.js applications supporting 50K+ users, implementing server-side caching and scalable REST APIs.",
        "Led Angular-to-React migration initiatives, improving maintainability and standardizing reusable UI patterns across applications.",
        "Engineered end-to-end features across React, Java, and Python microservices and optimized SQL queries and REST endpoints for large datasets.",
        "Achieved 100% Section 508 accessibility compliance and improved page performance by 25% through collaboration with design and QA teams.",
        "Mentored junior engineers, conducted 60+ code reviews, and implemented CI/CD pipelines that reduced deployment time by 40%."
      ]
    },
    {
      "company": "Cognizant Softvision, Atlanta, Georgia",
      "role": "Software Developer, Full Stack",
      "period": "Mar 2021 – Jan 2023",
      "bullets": [
        "Applied Java, SOLID principles, and CLEAN architecture to design scalable, maintainable applications, reducing technical debt and boosting long-term reliability.",
        "Developed SQL/NoSQL databases and 25+ RESTful APIs with Java/Spring Boot, improving query performance by 30% and accelerating feature delivery by 20%.",
        "Constructed React applications with Context API, Redux, and React Router, enhancing UI responsiveness and improving user satisfaction by double.",
        "Implemented and documented Node.js/Nest.js APIs with Swagger UI, reducing developer onboarding time by 40%."
      ]
    },
    {
      "company": "Honeywell International Inc, Atlanta, Georgia",
      "role": "Software Developer, Frontend Developer",
      "period": "May 2018 – Mar 2021",
      "bullets": [
        "Built and maintained enterprise web apps with React, Redux, Java, and Spring Boot, improving scalability and system uptime.",
        "Integrated secure APIs with OAuth2 SSO, Twilio 2FA, and SOAP/REST services, supporting 1000+ users.",
        "Migrated legacy Angular apps to React/TypeScript, boosting performance by 40% and enabling reusable component libraries.",
        "Helped optimize SQL/NoSQL databases (Postgres, MySQL, MongoDB, CosmosDB) to ensure 99% availability and faster queries for SaaS applications.",
        "Conducted usability testing on prototypes, improving customer satisfaction scores by 20% and reducing post-launch revisions."
      ]
    }
  ],
  "education": [
    {
      "school": "Georgia Institute of Technology - Atlanta",
      "degree": "Bachelor of Science: Computer Science",
      "year": "2018"
    }
  ]
}
