// Auto-generated by scripts/sync-resume.ts — do not edit manually.
// Update public/resume.pdf then run `npm run sync-resume` to regenerate.

export type Experience = {
  company: string
  role: string
  period: string
  bullets: string[]
}

export type Education = {
  school: string
  degree: string
  year: string
}

export type ResumeData = {
  hasDocx: boolean
  experience: Experience[]
  education: Education[]
}

export const resume: ResumeData = {
  "hasDocx": false,
  "experience": [
    {
      "company": "Deloitte",
      "role": "Full Stack Web Developer",
      "period": "May 2023 – Jan 2026",
      "bullets": [
        "Built reusable product and content modules across search and checkout flows, reducing UI development time by 30%.",
        "Improved Core Web Vitals by implementing SSR, caching, and code-splitting, reducing load times by 25–30%.",
        "Delivered customer-facing modules for a government platform serving 10K+ users.",
        "Mentored junior engineers, conducted 60+ code reviews, and reduced deployment time by 40% via CI/CD pipelines.",
        "Achieved 100% Section 508 accessibility compliance and improved page performance by 25%."
      ]
    },
    {
      "company": "Cognizant Softvision",
      "role": "Software Developer, Full Stack",
      "period": "Mar 2021 – Jan 2023",
      "bullets": [
        "Developed 25+ RESTful APIs with Java/Spring Boot, improving query performance by 30%.",
        "Accelerated feature delivery by 20% through optimized SQL/NoSQL database design.",
        "Built React applications with Context API and Redux, doubling user satisfaction scores.",
        "Implemented Node.js/Nest.js APIs with Swagger UI, reducing developer onboarding time by 40%."
      ]
    },
    {
      "company": "Honeywell International Inc",
      "role": "Software Developer, Frontend Developer",
      "period": "May 2018 – Mar 2021",
      "bullets": [
        "Migrated legacy Angular apps to React/TypeScript, boosting performance by 40%.",
        "Integrated secure APIs with OAuth2 SSO and Twilio 2FA, supporting 1000+ users.",
        "Optimized SQL/NoSQL databases to ensure 99% availability for SaaS applications.",
        "Conducted usability testing on prototypes, improving customer satisfaction scores by 20%.",
        "Built and maintained enterprise web apps with React, Redux, Java, and Spring Boot."
      ]
    }
  ],
  "education": [
    {
      "school": "Georgia Institute of Technology",
      "degree": "Bachelor of Science: Computer Science",
      "year": "2018"
    }
  ]
}
