import Anthropic from '@anthropic-ai/sdk'
import fs from 'fs'
import path from 'path'

// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse = require('pdf-parse') as (buf: Buffer) => Promise<{ text: string }>

const PDF_PATH = path.join(process.cwd(), 'public', 'resume.pdf')
const OUT_PATH = path.join(process.cwd(), 'data', 'resume.ts')

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.log('sync-resume: ANTHROPIC_API_KEY not set — skipping (using existing data/resume.ts)')
    return
  }

  if (!fs.existsSync(PDF_PATH)) {
    console.log('sync-resume: public/resume.pdf not found — skipping')
    return
  }

  console.log('sync-resume: extracting text from resume.pdf...')
  const buffer = fs.readFileSync(PDF_PATH)
  const { text } = await pdfParse(buffer)

  console.log('sync-resume: parsing with Claude...')
  const client = new Anthropic()

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 2048,
    messages: [
      {
        role: 'user',
        content: `Extract structured resume data from the text below. Return ONLY a valid JSON object — no markdown fences, no explanation — matching this exact shape:

{
  "skills": ["string"],
  "experience": [
    {
      "company": "string",
      "role": "string",
      "period": "string (e.g. '2022 – Present')",
      "bullets": ["string"]
    }
  ],
  "education": [
    {
      "school": "string",
      "degree": "string",
      "year": "string (4-digit year)"
    }
  ]
}

For "skills", extract a flat list of distinct technical skills (languages, frameworks, tools, platforms) mentioned anywhere in the resume. Each entry should be a short noun phrase (e.g. "React", "TypeScript", "PostgreSQL"). Do not include soft skills.

Resume text:
${text}`,
      },
    ],
  })

  const block = message.content[0]
  if (block.type !== 'text') throw new Error('Unexpected Claude response type')

  let parsed: { skills: unknown[]; experience: unknown[]; education: unknown[] }
  try {
    parsed = JSON.parse(block.text)
  } catch {
    throw new Error(`Claude returned invalid JSON:\n${block.text}`)
  }

  const output = `// Auto-generated by scripts/sync-resume.ts — do not edit manually.
// Update public/resume.pdf then run \`npm run sync-resume\` to regenerate.

export type Experience = {
  company: string
  role: string
  period: string
  bullets: string[]
}

export type Education = {
  school: string
  degree: string
  year: string
}

export type ResumeData = {
  hasDocx: boolean
  experience: Experience[]
  education: Education[]
}

export const resume: ResumeData = ${JSON.stringify({ hasDocx: false, ...parsed }, null, 2)}
`

  fs.writeFileSync(OUT_PATH, output)
  console.log('sync-resume: data/resume.ts updated successfully')
}

main().catch((err) => {
  console.error('sync-resume: failed —', err.message)
  // Exit cleanly so the build continues with existing data/resume.ts
})
